name: share_screenshot_widget
description: This plugin allows Flutter apps to Sharing widget as Screenshot in (WhatsApp,Telegram, Instagram, Facebook Messenger).
version: 0.0.3
homepage: https://github.com/736hsn/share_widgets

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

#  dartdoc: ^6.1.4
  share_plus: ^6.3.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
